<?php
/**
 * Feature: IndexNow.
 *
 * Hooks `transition_post_status`; when a public-post-type post moves to
 * `publish`, fires a non-blocking POST to api.indexnow.org so Bing and Yandex
 * begin re-crawling the URL within minutes.
 *
 * The IndexNow API key is configured via the settings page (option name
 * `agent_ready_indexnow_key`) and served at `/{key}.txt` for ownership
 * verification per the IndexNow protocol.
 *
 * @package AgentReady
 */

namespace AgentReady;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_action( 'transition_post_status', __NAMESPACE__ . '\\indexnow_on_publish', 10, 3 );
add_action( 'init', __NAMESPACE__ . '\\handle_indexnow_key_request' );

/**
 * Get the user-configured IndexNow key.
 *
 * The key is generated by the user at https://www.bing.com/webmasters/indexnow
 * and pasted into the Agent-Ready settings page. Returns an empty string when
 * unset — callers must bail rather than ping IndexNow without a key.
 *
 * @return string
 */
function get_indexnow_key(): string {
	$key = get_option( 'agent_ready_indexnow_key', '' );
	return is_string( $key ) ? trim( $key ) : '';
}

/**
 * Sanitize the IndexNow key on save.
 *
 * Per the IndexNow protocol, valid keys are 8-128 chars of [a-zA-Z0-9-].
 * Empty input is allowed (clears the setting).
 *
 * @param mixed $value
 * @return string
 */
function sanitize_indexnow_key( $value ): string {
	if ( ! is_string( $value ) ) {
		return '';
	}
	$value = trim( $value );
	if ( $value === '' ) {
		return '';
	}
	return preg_match( '/^[a-zA-Z0-9-]{8,128}$/', $value ) ? $value : '';
}

/**
 * Serve the IndexNow key file at /{key}.txt for ownership verification.
 *
 * @return void
 */
function handle_indexnow_key_request(): void {
	if ( ! is_feature_enabled( 'indexnow' ) ) {
		return;
	}

	if ( empty( $_SERVER['REQUEST_URI'] ) ) {
		return;
	}

	$key = get_indexnow_key();
	if ( $key === '' ) {
		return;
	}

	$path = wp_parse_url( sanitize_text_field( wp_unslash( $_SERVER['REQUEST_URI'] ) ), PHP_URL_PATH );
	if ( ! is_string( $path ) ) {
		return;
	}

	if ( $path !== '/' . $key . '.txt' ) {
		return;
	}

	nocache_headers();
	header( 'Content-Type: text/plain; charset=utf-8' );
	// Plain-text body served as text/plain. $key is sanitized via
	// sanitize_indexnow_key() to /^[a-zA-Z0-9-]{8,128}$/ — no HTML possible.
	// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
	echo $key;
	exit;
}

/**
 * Ping IndexNow for Bing/Yandex instant indexing.
 *
 * @param string $url URL to submit for re-crawl.
 * @return bool True if dispatched, false if precondition failed.
 */
function ping_indexnow( string $url ): bool {
	$host = wp_parse_url( home_url(), PHP_URL_HOST );
	if ( ! $host ) {
		return false;
	}

	$key = get_indexnow_key();
	if ( $key === '' ) {
		return false;
	}

	$response = wp_remote_post(
		'https://api.indexnow.org/indexnow',
		array(
			'body'     => wp_json_encode(
				array(
					'host'    => $host,
					'key'     => $key,
					'urlList' => array( $url ),
				)
			),
			'headers'  => array( 'Content-Type' => 'application/json' ),
			'timeout'  => 5,
			'blocking' => false,
		)
	);

	return ! is_wp_error( $response );
}

/**
 * Hook into post publish/update to ping IndexNow.
 *
 * @param string   $new_status New post status.
 * @param string   $old_status Previous post status.
 * @param \WP_Post $post       Post object.
 * @return void
 */
function indexnow_on_publish( string $new_status, string $old_status, \WP_Post $post ): void {
	if ( ! is_feature_enabled( 'indexnow' ) ) {
		return;
	}

	if ( $new_status !== 'publish' ) {
		return;
	}

	if ( wp_is_post_revision( $post->ID ) || wp_is_post_autosave( $post->ID ) ) {
		return;
	}

	$public_post_types = get_post_types( array( 'public' => true ) );
	if ( ! in_array( $post->post_type, $public_post_types, true ) ) {
		return;
	}

	$url = get_permalink( $post );
	if ( ! $url ) {
		return;
	}

	ping_indexnow( $url );
}
